# Generated by Django 5.2.3 on 2025-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="source",
            field=models.CharField(
                choices=[("ADMIN", "admin"), ("CMD", "cmd"), ("API", "api"), ("TMDB", "tmdb")],
                default="API",
                max_length=50,
            ),
        ),
    ]
