# Generated by Django 5.2.3 on 2025-06-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_review_authorreview_moviereview"),
        ("users", "0002_alter_baseuser_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectator",
            name="favorite_movies",
            field=models.ManyToManyField(blank=True, related_name="favorite_spectators", to="movies.movie"),
        ),
    ]
