# Generated by Django 5.2.3 on 2025-06-21 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cinema", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="authors",
            field=models.ManyToManyField(related_name="movies", to="users.author"),
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="cinema.genre"),
        ),
        migrations.AddField(
            model_name="authorreview",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="users.author"
            ),
        ),
        migrations.AddField(
            model_name="authorreview",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors_reviews",
                to="users.spectator",
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies_reviews",
                to="users.spectator",
            ),
        ),
        migrations.AddField(
            model_name="moviereview",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="cinema.movie"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="authorreview",
            unique_together={("author", "created_by")},
        ),
        migrations.AlterUniqueTogether(
            name="moviereview",
            unique_together={("movie", "created_by")},
        ),
    ]
