# Generated by Django 5.2.3 on 2025-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="adult_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="original_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="original_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
    ]
