# Generated by Django 5.2.3 on 2025-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_movie_adult_content_movie_original_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="source",
            field=models.CharField(
                choices=[("ADMIN", "admin"), ("TMDB", "tmdb")], default="TMDB", max_length=50
            ),
        ),
    ]
