# Generated by Django 5.2.3 on 2025-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_movie_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="source",
            field=models.CharField(
                choices=[("ADMIN", "admin"), ("CMD", "cmd"), ("API", "api"), ("TMDB", "tmdb")],
                default="API",
                max_length=50,
            ),
        ),
    ]
