# Generated by Django 5.2.3 on 2025-06-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_movie_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movie",
            unique_together={("title", "original_title", "release_date")},
        ),
    ]
