# Generated by Django 5.2.3 on 2025-06-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0006_alter_movie_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="rating",
        ),
    ]
