# Generated by Django 5.2.3 on 2025-06-19 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="movies", to="users.author"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="movies", to="movies.genre"
            ),
        ),
    ]
