# Generated by Django 5.2.3 on 2025-06-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_rating",
            field=models.CharField(
                choices=[
                    ("ONE_STAR", 1),
                    ("TWO_STARS", 2),
                    ("THREE_STARS", 3),
                    ("FOUR_STARS", 4),
                    ("FIVE_STARS", 5),
                ],
                default="FIVE_STARS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "draft"),
                    ("IN_REVIEW", "in_review"),
                    ("PUBLISHED", "published"),
                    ("ARCHIVED", "archived"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
