# Generated by Django 5.2.3 on 2025-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_created_at_movie_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONE_STAR", 1),
                    ("TWO_STARS", 2),
                    ("THREE_STARS", 3),
                    ("FOUR_STARS", 4),
                    ("FIVE_STARS", 5),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
