# Generated by Django 5.2.3 on 2025-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movie_movie_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="movie_rating",
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
