# Generated by Django 5.2.3 on 2025-06-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_remove_movie_movie_rating_alter_movie_rating"),
        ("users", "0002_alter_baseuser_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="author",
        ),
        migrations.AddField(
            model_name="movie",
            name="author",
            field=models.ManyToManyField(related_name="movies", to="users.author"),
        ),
    ]
