# Generated by Django 5.2.3 on 2025-06-20 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_review_authorreview_moviereview"),
        ("users", "0003_spectator_favorite_movies"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_created",
                to="users.spectator",
            ),
            preserve_default=False,
        ),
    ]
