# Generated by Django 5.2.3 on 2025-06-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_review_created_by"),
        ("users", "0003_spectator_favorite_movies"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorreview",
            options={},
        ),
        migrations.AlterModelOptions(
            name="moviereview",
            options={},
        ),
        migrations.RemoveField(
            model_name="review",
            name="created_by",
        ),
        migrations.AddField(
            model_name="authorreview",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors_reviews",
                to="users.spectator",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moviereview",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies_reviews",
                to="users.spectator",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="authorreview",
            unique_together={("author", "created_by")},
        ),
        migrations.AlterUniqueTogether(
            name="moviereview",
            unique_together={("movie", "created_by")},
        ),
    ]
