# Generated by Django 5.2.3 on 2025-06-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_alter_authorreview_options_alter_moviereview_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
