# Generated by Django 5.2.3 on 2025-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_remove_movie_is_active_alter_review_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="author",
            new_name="authors",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="movies.genre"),
        ),
    ]
